<?php

// Settings tab
function ao_ccss_settings() {

  // Attach globals
  global $ao_css_defer;
  global $ao_ccss_key;

  ?>
  <div class="wrap">
    <h1><?php _e('Autoptimize Power-Up: CriticalCSS Settings', 'ao_ccss'); ?></h1>

      <?php
      // Print AO settings tabs
      echo autoptimizeConfig::ao_admin_tabs();

      // Check CriticalCSS license
      $licstat = ccss_license_check('ao_critcsscom', '0.9', $ao_ccss_key);

      // Make sure dir to write ao_ccss exists and is writable
      if (!is_dir(AO_CCSS_DIR)) {
        $mkdirresp = @mkdir(AO_CCSS_DIR, 0775, true);
        $fileresp  = file_put_contents(AO_CCSS_DIR . 'index.html','<html><head><meta name="robots" content="noindex, nofollow"></head><body>Generated by <a href="http://wordpress.org/extend/plugins/autoptimize/" rel="nofollow">Autoptimize</a></body></html>');
        if ((!$mkdirresp) || (!$fileresp)) {
          ?><div class="notice-error notice"><p><?php
          _e("Could not create the required directory. Make sure the webserver can write to the wp-content directory.", "ao_ccss");
          ?></p></div><?php
        }
      }

      // Check for Autoptimize
      if (!defined('AUTOPTIMIZE_CACHE_NOGZIP')) {
        ?><div class="notice-error notice"><p><?php
        _e('Oops! Please install and activate Autoptimize first.', 'ao_css');
        ?></p></div><?php
        exit;
      } else if (!$ao_css_defer) {
        ?><div class="notice-error notice"><p><?php
        _e("Oops! Please <strong>activate the \"Inline and Defer CSS?\" option</strong> on Autoptimize's main settings page.", 'ao_css');
        ?></p></div><?php
      } else if (version_compare(get_option("autoptimize_version"),"2.2.0")===-1) {
        ?><div class="notice-error notice"><p><?php
        _e('Oops! It looks you need to upgrade to Autoptimize 2.2.0 or higher to use this power-up.', 'ao_css');
        ?></p></div><?php
      }
      ?>

      <!-- TODO: here goes more and more settings... -->

      <!-- BEGIN: Settings Debug -->
      <ul>
        <li class="itemDetail">
          <h2 class="itemTitle"><?php _e('Debug Stuff', 'ao_ccss'); ?></h2>
          <h4>Current Settings:</h4>
          <table class="form-table">
            <tr valign="top">
              <th scope="row">
                autoptimize_ccss_key:
              </th>
              <td>
                <?php echo (empty($ao_ccss_key) ? 'empty' : $ao_ccss_key); ?>
              </td>
            </tr>
          </table>
          <hr />
          <h4>Transients:</h4>
          <table class="form-table">
            <tr valign="top">
              <th scope="row">
                <?php echo 'ao_ccss_lic_status_' . md5($ao_ccss_key) . ':'; ?>
              </th>
              <td>
                <?php echo (empty(get_transient('ao_ccss_lic_status_' . md5($ao_ccss_key))) ? 'empty' : get_transient('ao_ccss_lic_status_' . md5($ao_ccss_key))); ?>
              </td>
            </tr>
          </table>
          <hr />
          <h4>Array Content: autoptimize_ccss_queue</h4>
          <pre>
            <?php print_r(get_option('autoptimize_ccss_queue')); ?>
          </pre>
        </li>
      </li>
      <!-- END: Settings Debug -->

  </div>
  <?php
}

?>